name: ${project.artifactId}
main: ${main.class}
version: ${project.version}
api-version: 1.13
author: kangarko
softdepend: [AuthMe, Boss, DiscordSRV, Factions, Feudal, Essentials, EssentialsX, LegacyFactions, LuckPerms, MVdWPlaceholderAPI, NashornPlus, Multiverse-Core, MythicMobs, Nicky, PlaceholderAPI, ProtocolLib, SimpleClans, Towny, TownyChat, Vault, WorldEdit]
#
# The commands are built at runtime so you can change them easily within the settings.
# Do not change anything in here, you will break the plugin and get no support.
#
commands: 
permissions:
  corearena.command.join:
    default: true
  corearena.command.leave:
    default: true
  corearena.command.list:
    default: true
  corearena.command.rewards:
    default: true